Develop
AdrianCzarnowski/homeBudget pull request #5
Opened 2024-05-24 08:15 UTC by AdrianCzarnowski

2024-05-31 10:30 UTC, adamos98 requested changes

2024-05-31 10:30 UTC, adamos98 commented on src/main/java/projects/adrian/homebudget/repository/BudgetRepository.java
> +//    List<BudgetEntity> findByUser(String name);
If it is not needed, delete it :)

2024-06-04 05:02 UTC, AdrianCzarnowski commented on src/main/java/projects/adrian/homebudget/repository/BudgetRepository.java
> +//    List<BudgetEntity> findByUser(String name);
done

2024-06-04 07:10 UTC, adamos98 approved these changes

2024-06-25 18:57 UTC, merged